import os
import uuid
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"

def get_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def save_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

def append_log(entry):
    entries = get_log()
    entries.append(entry)
    save_log(entries)

def groq_signal(text):
    prompt = f"""Analyze the following text and determine if it was written by a human or generated by AI.

Text:
{text}

Respond with ONLY a JSON object in this exact format:
{{"ai_score": 0.0, "reasoning": "brief explanation"}}

Where ai_score is a float from 0.0 (definitely human) to 1.0 (definitely AI).
No other text, no markdown, just the JSON object."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )
    
    result = json.loads(response.choices[0].message.content.strip())
    return result["ai_score"]

def stylo_signal(text):
    import re
    
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 2:
        return 0.5
    
    words_per_sentence = [len(s.split()) for s in sentences]
    mean_len = sum(words_per_sentence) / len(words_per_sentence)
    variance = sum((x - mean_len) ** 2 for x in words_per_sentence) / len(words_per_sentence)
    
    words = text.lower().split()
    unique_words = set(words)
    ttr = len(unique_words) / len(words) if words else 0.5
    
    punctuation_count = sum(1 for c in text if c in '",;:()!?—-')
    punct_density = punctuation_count / len(words) if words else 0

    # Low variance = AI-like uniformity → high score
    variance_score = max(0.0, 1.0 - (variance / 50))
    # Low TTR = repetitive vocabulary → AI-like → high score
    ttr_score = max(0.0, 1.0 - ttr)
    # Low punctuation = AI-like → high score
    punct_score = max(0.0, 1.0 - (punct_density / 0.1))

    stylo_score = (variance_score * 0.4) + (ttr_score * 0.4) + (punct_score * 0.2)
    return round(min(1.0, max(0.0, stylo_score)), 3)


def generate_label(attribution, confidence):
    pct = round(confidence * 100)
    if attribution == "likely_ai":
        return (
            f"⚠️ AI-Generated Content Detected — Our system found strong indicators "
            f"that this content was likely AI-generated (confidence: {pct}%). "
            f"If this is incorrect, you can file an appeal."
        )
    elif attribution == "uncertain":
        return (
            f"🔍 Attribution Unclear — Our system could not confidently determine "
            f"whether this content was human or AI-written (confidence: {pct}%). "
            f"It will be treated as unverified. You may file an appeal."
        )
    else:
        return (
            f"✅ Likely Human-Written — Our system found no strong indicators of "
            f"AI generation (confidence: {pct}%). "
            f"This content has been marked as likely human-authored."
        )
    
@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    llm_score = groq_signal(text)
    stylo_score = stylo_signal(text)
    confidence = round((llm_score * 0.6) + (stylo_score * 0.4), 3)

    if confidence >= 0.70:
        attribution = "likely_ai"
    elif confidence >= 0.40:
        attribution = "uncertain"
    else:
        attribution = "likely_human"

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "confidence": confidence,
        "attribution": attribution,
        "label": generate_label(attribution, confidence),
        "status": "classified",
        "appeal_reasoning": None,
    }
    append_log(entry)

    return jsonify({
    "content_id": content_id,
    "attribution": attribution,
    "confidence": confidence,
    "label": entry["label"],
})

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = data["content_id"]
    creator_reasoning = data["creator_reasoning"]

    entries = get_log()
    found = False
    for entry in entries:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = creator_reasoning
            entry["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()
            found = True
            break

    if not found:
        return jsonify({"error": "content_id not found"}), 404

    save_log(entries)

    return jsonify({
        "message": "Appeal received. Your content has been marked as under review.",
        "content_id": content_id,
        "status": "under_review",
    })

@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})

if __name__ == "__main__":
    app.run(debug=True)